# the cert secret mounted but not used
# the certs are got from the image.
# see dockerfile (CMD ["/webhook", "--tls-cert", "/certs/webhook.crt", "--tls-key", "/certs/webhook.key"])
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-webhook-server
  namespace: image-webhook
  labels:
    app: cdi-images-caching-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdi-images-caching-svc
  template:
    metadata:
      labels:
        app: cdi-images-caching-svc
    spec:
      containers:
      - name: web-hook
        image: quay.io/hgao/cdi-images-caching:1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
        volumeMounts:
        - mountPath: /etc/webhooks/cdi-images-caching-certs
          name: cdi-images-caching-certs
      volumes:
      - name: cdi-images-caching-certs
        secret:
          secretName: webhook-secret

